MicrosoftEdge/JsDbg

- server/JsDbg.Gdb/JsDbg.py
> [gdb] Remove duplicate definition of SSymbolResult

- extensions/dbgobject/descriptions/descriptions.js
Only single bit scalar values should get a true/false description. Single bit enums should work like all other enums.
> Fix descriptions for single bit enums

- server/JsDbg.Gdb/JsDbg.py
This comes up here, for example:
https://cs.chromium.org/chromium/src/third_party/blink/renderer/core/layout/layout_box.h?q=LayoutBox&sq=package:chromium&g=0&l=1812
Without this change we throw an exception, so we don't get any LayoutBox
fields. Longer-term, we need to find a way to handle anonymous unions.
> [gdb] Handle anonymous fields in GetAllFields and LookupField

- server/jsdbg.sln
This was my oversight in 1703565bb0460da22bd6905df080011fbcada8ff
> Build JsDbg.Windows by default

- extensions/target-specific/stl-helpers/stl-helpers.js
I based this on https://cs.chromium.org/chromium/src/third_party/libcxx-pretty-printers/printers.py
and it seems to work
> Support libc++ maps in stl-helpers

- server/JsDbg.Gdb/GdbDebugger.cs
- server/JsDbg.Gdb/JsDbg.py
Also removes an unused variable.
> [gdb] Support debugger events

- extensions/dbgobject/core/dbgobject.js
- extensions/jsdbg/core/jsdbg.js
- server/JsDbg.Core/IDebugger.cs
- server/JsDbg.Core/WebServer.cs
- server/JsDbg.Windows/DiaDebugger.cs
> Support an optional namespace for looking up globals

- server/JsDbg.Gdb/GdbDebugger.cs
- server/JsDbg.Gdb/JsDbg.py
> [gdb] Implement getting/setting processes and threads

- server/jsdbg.sln
This was done using "dotnet sln jsdbg.sln add JsDbg.Gdb/JsDbg.Gdb.csproj"
> Add JsDbg.Gdb to the .sln file

- extensions/dbgobject/core/dbgobject.js
- extensions/jsdbg/core/jsdbg.js
- extensions/target-specific/chromium/ax-tree/ax-tree.js
- server/JsDbg.Core/IDebugger.cs
- server/JsDbg.Core/WebServer.cs
- server/JsDbg.Windows/DiaDebugger.cs
And use it in ax-tree.js. This makes the lookup work on GDB.
> Rename nameSpace to scope for LookupGlobalSymbol

- server/JsDbg.Gdb/GdbDebugger.cs
To match c0a9c162f1ccc05f270c469bddd46ab52feb3fa5
> [gdb] Rename nameSpace to scope

- extensions/target-specific/chromium/blink/blink-helpers/blink-helpers.js
They were renamed in https://crrev.com/c/1582872
> [blink-helpers] Add new names for NGPhysical{Offset,Size}

- extensions/object-diff/index.html
isArray was moved to DbgObjectType in a3420cf90a77f4efe7db0d0dd13de5c612c0b057
> [object-diff] Fix "show nested fields"

- server/JsDbg.Gdb/GdbDebugger.cs
Similar to what the Windows implementation outputs.
I also turned off stderr output by default because otherwise
the GDB window gets very crowded with the message output.
> [gdb] Add debugger messages so the user can see progress

- server/JsDbg.Core/JsDbg.Core.csproj
I forgot to do this in b24c7fc9f8376449a486c1799450450a54854b51 :(
> Add MimeMappings.cs to the csproj file

- server/JsDbg.Core/WebServer.cs
Cherrypicks the WebServer.cs change from the gdb branch
from 5d35e39b4d558738b8c56b95ace97de544b28aaa
> Add PrintDebuggerMessages field to master

- extensions/target-specific/chromium/blink/blink-helpers/blink-helpers.js
- extensions/target-specific/chromium/cclayertree/cclayertree.js
This ports those changes from the jsdbg_gdb_support branch.
> Add the scope arguments for g_frame_map and g_view_map

- extensions-inprogress/struct-viz/index.html
- extensions/dbgobject-inspector/dbgobject-inspector.css
- extensions/jsdbg/loading-indicator/loading-indicator.css
- extensions/jsdbg/styles/common.css
- extensions/tree-drawing/talltree.css
- extensions/tree-inspector/field-selector/field-selector.css
> Specify fallback fonts if Segue UI or Consolas don't exist

- server/JsDbg.Core/WebServer.cs
Now that FileCache works on Linux (f1773d5efbc67a7d2a7f803b138bcdfaa0791c74),
make the gdb branch use it.
> [gdb] Use FileCache

- server/JsDbg.Gdb/JsDbg.Gdb.csproj
> [gdb] Copy extensions and python script to output directory

- extensions/target-specific/chromium/ax-tree/extension.json
- extensions/target-specific/chromium/blink/blink-helpers/extension.json
- extensions/target-specific/chromium/blink/dom-tree/extension.json
- extensions/target-specific/chromium/blink/extension.json
- extensions/target-specific/chromium/blink/fragment-tree/extension.json
- extensions/target-specific/chromium/blink/layout-object-tree/extension.json
- extensions/target-specific/chromium/blink/wtf-helpers/extension.json
- extensions/target-specific/chromium/cclayertree/extension.json
- extensions/target-specific/chromium/chromium-helpers/chromium-helpers.js
- extensions/target-specific/chromium/chromium-helpers/extension.json
- extensions/target-specific/chromium/compositorframe/extension.json
- extensions/target-specific/chromium/extension.json
- extensions/target-specific/chromium/gfx-type-helpers/extension.json
- extensions/target-specific/chromium/win-d3d11-angletextures/extension.json
They behave similar to browser_tests in many ways.
> Also load chromium extensions for content_browsertests

- server/JsDbg.Gdb/JsDbg.py
This is required to support std::basic_string
> [gdb] Support anonymous structs as well as unions

- docs/CONTRIBUTING.md
Mostly for when we merge this branch to master.
> [gdb] Add build and debugging instructions

- extensions/target-specific/stl-helpers/stl-helpers.js
String printer based on
https://cs.chromium.org/chromium/src/third_party/libcxx-pretty-printers/printers.py
> [stl] Support libcxx pair and basic_string

- server/JsDbg.Gdb/GdbDebugger.cs
No behavior change but makes debugging JsDbg easier.
> [gdb] Format pointers in hex for Python

- extensions/dbgobject/core/dbgobject.js
This is necessary for Linux in multiple inheritance situations,
e.g. for the ax-tree extension (content::BrowserAccessibilityManagerAuraLinux)
Fixes: #101
> Make DbgObject.vcast ignore a nonzero displacement

- server/JsDbg.Gdb/JsDbg.py
JsDbg's memorycache does not handle unaligned loads well.
So this change makes GetAllFields and LookupField return
aligned offsets for bitfields.
(This comes up very visibly in WTF::StringImpl::is_8bit_,
which can often be wrong without this change)
> [gdb] Make fields return aligned offsets for bitfields

- docs/CONTRIBUTING.md
- server/JsDbg.Gdb/JsDbg.py
This should make finding the binary and extensions more
robust.
> [gdb] Search for JsDbg.Gdb and extensions relative to JsDbg.py

- extensions/memorycache/memorycache.js
Let me know if this indentation of the second line of the if is OK
> [memorycache] Support unaligned memory access

- server/JsDbg.Gdb/JsDbg.py
No need to call gdb.lookup_type for every base class.
> [gdb] Make GetBaseTypes faster

- extensions/target-specific/chromium/blink/blink-helpers/blink-helpers.js
- extensions/target-specific/chromium/blink/fragment-tree/fragment-tree.js
- extensions/target-specific/chromium/blink/layout-object-tree/layout-object-tree.js
Look through legacy/NG boundaries to find more fragments, so we
can show a more complete fragment tree.
> [fragment-tree] Look harder for fragments

- server/JsDbg.Gdb/JsDbg.py
It seems that in some circumstances (I haven't figured out
which ones) the other approach doesn't work.
> Use gdb.lookup_type and enumval for enums

- debian/control
- debian/rules
- server/JsDbg.Gdb/JsDbg.Gdb.csproj
- server/JsDbg.Gdb/JsDbg.py
- server/JsDbg.Gdb/Makefile
- server/JsDbg.Gdb/create_package.sh
This pull request bundles a series of commits for various improvements
to the Makefiles/debian packaging scripts. See the individual commit
descriptions for details.
> [gdb] Various build system changes

- server/JsDbg.Gdb/JsDbg_test.py
I forgot to run the test when I added the GDB parameter :(
(in commit a39c4908adf5fcdb6d1c334b08d8b7eebbdf5326)
> [gdb] Fix JsDbg_test

- server/JsDbg.Gdb/JsDbg.py
- server/JsDbg.Gdb/testsuite/jsdbg.tests/basic.exp
- server/JsDbg.Stdio/JsDbgTypes.py
- server/JsDbg.Stdio/StdioDebugger.cs
Makes it use a class for its return value.
> [gdb] Make LookupSymbolName follow the style of the other functions

- server/JsDbg.Gdb/Makefile
Forgot to add these to the tar when I factored them out :(
> [gdb] Add missing files to .tar.bz2

- debian/changelog
- debian/control
- docs/README.md
Mention how to upgrade and the date of the last rebuild.
> [gdb] Update .deb version and doc improvements

- extensions/object-diff/index.html
Otherwise templates won't display correctly.
> [object-diff] Escape type and field names
