extensions/catalog/catalog.js, extensions/extensions-dashboard/extensions-dashboard.js, extensions/jsdbg/core/jsdbg.js, server/JsDbg.Core/PersistentStore.cs, server/JsDbg.Core/WebServer.cs
The persistent storage feature was inadvertently broken when it was moved from cloud based storage to local machine storage. The bug happens primary during the initial retrieval (get) from the persistent store - which happens on every page load - and is due to missing the necessary jsdbg persistent store file on the user's local machine. The fix is to check for the existance of the file, and if it doesn't exist, return an empty JSON string to represent the data (or lack thereof) in the persistent store.
In addition, this change removes dead code related to tracking the user's name and domain. This feature was removed from JsDbg prior to open-sourcing, but some parameters (that are now always null or empty string) were not removed from related functions.
Fixes #1
=> User customization via "edit" and "extend" buttons (aka persistent store) is broken

server/JsDbg.VisualStudio/JsDbg.VisualStudio.csproj, server/JsDbg.VisualStudio/source.extension.vsixmanifest
It needs a prerequisite entry for VS extension development.
Also, it seems that the CommandBars reference was incorrectly (?)
added, this now looks the same as the Microsoft.VisualStudio.Debugger.Interop
entry.
=> Make JsDbg.VisualStudio build with a default installation of VS2017

extensions/dbgobject/core/dbgobject.js, extensions/jsdbg/core/jsdbg.js, server/JsDbg.Core/IDebugger.cs, server/JsDbg.Core/ITypeCacheDebuggerEngine.cs, server/JsDbg.Core/TypeCacheDebugger.cs, server/JsDbg.Core/WebServer.cs, server/JsDbg.VisualStudio/DebuggerEngine.cs, server/JsDbg.WinDbg/DebuggerEngine.cs
Currently, the global symbol lookup in the JsDbg server finds the first match and returns it to the client. However, there can be multiple global symbols that have the same symbol name (ex. msedge!instance), with each having a different type. In such cases, the global lookup may not find the correct symbol.
To support this case, an optional "typeName" parameter is being added to the DbgObject.global function, which allows extensions to explicitly specify the type of the global symbol they are looking for. This parameter gets passed all the way down to the server, and the server ensures that a global symbol of the corresponding type is returned (if present).
This type name based lookup is only supported when directly querying the symbol files using DIA APIs, and does not work with the …
=> Add support for differentiating global symbols that have the same name but different types

extensions/target-specific/chromium/blink/blink-helpers/blink-helpers.js
Basically adds an override for all the bitfields in
https://cs.chromium.org/chromium/src/out/Debug/gen/third_party/blink/renderer/core/style/computed_style_base.h?type=cs&sq=package:chromium&g=0
Plus StyleSelfAlignmentData and StyleContentAlignmentData.
=> [blink] Add type overrides for ComputedStyleBase

extensions/promise/promise.js, extensions/target-specific/chromium/ax-tree/ax-tree.js, extensions/target-specific/chromium/chromium-helpers/chromium-helpers.js
This change updates the AXTree code to use either the new AXTreeManager or the older g_ax_tree_id_map for constructing the AXTree.
=> Fixing AXTree code to refer to new AXTreeManager instance

server/JsDbg.Gdb/JsDbg.py
Restores the code that was accidentally deleted in
160a705f46bcf014e727bbedde9e52012805a41d
=> Add a gdb command to run jsdbg, instead of running on import

server/JsDbg.Gdb/JsDbg.py
There's no hex() method in Python 2.
=> [gdb] Use binascii.hexlify for Python 2 compat

server/JsDbg.Gdb/GdbDebugger.cs
There are no {} around the response.
=> [gdb] Fix LookupTypeSize response parsing

server/JsDbg.Gdb/JsDbg.py
The latter does not work for variables with local linkage, such as
those in an anonymous namespace, which are a common usage for this
functionality (blink-helper's GetDocuments() needs it)
I've filed https://sourceware.org/bugzilla/show_bug.cgi?id=24474,
but this change will make this feature work until gdb is fixed.
=> [gdb] Use gdb.lookup_symbol instead of lookup_global_symbol

server/JsDbg.Gdb/GdbDebugger.cs
QueryDebuggerString returns the data without any prefix before
'{', so the data starts at 0, not 1.
=> [gdb] Fix off by one error

extensions/dbgobject/arrays/arrays.js
Otherwise, templates won't display correctly
=> Use the htmlName in error messages

server/JsDbg.Gdb/GdbDebugger.cs
This confuses the python script who interprets it as a comment.
I could fix it by writing to Console.Error but this does not seem
valuable enough to keep.
=> [gdb] Remove a line of debug output

server/JsDbg.Gdb/JsDbg.py
So that the lookup works also for enums that are not
an enum class.
And use .cast instead of .reinterpret_cast.
Both of these seems to be required at least for
blink::Node::NodeFlags.
=> [gdb] Also look up constants without the typename

extensions/target-specific/chromium/chromium-helpers/chromium-helpers.js, extensions/target-specific/chromium/compositorframe/compositorframe.js, extensions/target-specific/chromium/compositorframe/extension.json, extensions/target-specific/chromium/compositorframe/index.html, extensions/target-specific/chromium/extension.json, extensions/target-specific/chromium/gfx-type-helpers/gfx-type-helpers.js
This change implements a visualizer for compositorframe. Break into CompositorFrameSinkImpl::SubmitCompositorFrameInternal 
and then pass the address of &frame in the extension to see the contents of the frame.
on retail builds break into CompositorFrameSinkStubDispatch::Accept and pass 
&p_frame as the address to the extension.
Also included are some visualizers for gfx::Rect,gfx::Size and gfx::Transform
=> Inspector for a compositor frame

server/JsDbg.Gdb/GdbDebugger.cs
This accounts for the 2 words reserved for RTTI information. Because
the RTTI information is stored "before" the object itself, the vtable
pointer actually points to vtable + 2 pointers. See the link
in this commit for some more context.
DbgObject.symbol (and therefore DbgObject.vcast) requires displacement
to be 0 if you're logically at the beginning of the symbol.
=> [gdb] Set Displacement to 0 if it is 2*pointer size

extensions/target-specific/chromium/blink/blink-helpers/blink-helpers.js
To more easily go to the pointed object instead of requiring
two steps. Modeled after the std::unique_ptr extended field.
=> [blink] Add an extended field for DataRef

server/JsDbg.Core/WebServer.cs
This cherry-picks the logging-related parts of commits
7799d0577f713ae4734501fd58c1e8f6c2d2b93b and
160a705f46bcf014e727bbedde9e52012805a41d from the
jsdbg_gdb_support branch.
Writing to Error helps with gdb because Out is used for
communication between the server and gdb.
=> Write all logging to Console.Error

server/JsDbg.Gdb/JsDbg.py
Looks nicer that way (especially when STL is involved) and gdb doesn't
get confused.
=> [gdb] Use strip_typedefs when returning types

server/JsDbg.Gdb/JsDbg.py
This should be more likely to work for more people.
Probably still no long-term solution, though.
=> [gdb] Look for JsDbg under ~/JsDbg by default

extensions/dbgobject/type/dbgobject-type.js, extensions/target-specific/chromium/blink/wtf-helpers/wtf-helpers.js
There are two separate issues being fixed with this changes.
First, the .isUnsigned API on DbgObjectType is written incorrectly. This change fixes it work with unsigned values and all char types.
Second, the Text type description for WTF::StringImpl used to unconditionally treat the underlying string as being comprised of 8-bit characters. However, the string may contain 8-bit or 16-bit characters based on the is_8bit_ flag. This is also being fixed herewith so that the type description works for both Latin-1 and UTF-16 strings.
=> WTFHelpers: Handle both Latin-1 and UTF-16 strings

server/JsDbg.Gdb/JsDbg.py
PersistentStore now always uses the temp directory
=> Fix bad merge - persistent store directory is gone

server/JsDbg.Gdb/GdbDebugger.cs, server/JsDbg.Gdb/JsDbg.py
GDB doesn't actually need the module name, but JsDbg uses it for matching
extensions, so it is important to return a correct value.
=> [gdb] Return the correct module for LookupSymbolName

server/JsDbg.Gdb/JsDbg.py
This will make the default output more useful for regular users.
(stderr gets output when the JsDbg server crashes)
=> [gdb] Flip defaults for stderr and verbose

server/JsDbg.Core/WebServer.cs
=> Handle exceptions from ServeCurrentProcessThreads and GetAttachedProcesses

server/JsDbg.Gdb/JsDbg.py
rr renames the executable; make it match as well so that the
right extensions show up.
=> [gdb] Make the main module match when running under rr

server/JsDbg.Gdb/JsDbg.py
I put the rr support code in the wrong place; it needs to be
before lookup_objfile because that throws an exception when
the file is not found, so we never reached this code.
=> [gdb] Fix the rr code

extensions/target-specific/chromium/win-d3d11-angletextures/extension.json
Otherwise, the JS file fails to load on Linux, which is bad even if
the extension doesn't work there anyway.
=> [angletextures] Fix capitalization of angletextures.js

server/JsDbg.VisualStudio/JsDbg.VisualStudio.csproj
Uses a environment variable that seems to work (VSToolsPath) to find dependencies automatically.
=> Fix VS references

extensions/jsdbg/loader.js
Currently, if a JS file fails to load we hang forever even if
the current page actually doesn't need it. It seems better to
also add an error handler to consider it finished even if it
fails.
This is prompted by me noticing that angletextures.js is not loading
with a 404 error, which I have not debugged yet.
=> Handle failed loads of .js files more gracefully

server/JsDbg.Core/WebServer.cs, server/JsDbg.Gdb/JsDbg.py, server/JsDbg.Gdb/Program.cs
- Don't print debugger messages to stderr on Linux, but keep other stderr
output. Rationale: debugger messages get too verbose because they get
intermixed with your gdb session, but other stderr output is useful,
in particular the server URL gets printed to stderr.
- If the server crashes, show a message to the user and reset the jsdbg
global, so that typing jsdbg again will do the right thing.
=> [gdb] Various logging output improvements

server/JsDbg.Gdb/GdbDebugger.cs, server/JsDbg.Gdb/JsDbg.py
Also makes it more explicit that GetSymbolsInStackFrame
can return None when the frame is not found.
=> [gdb] Handle a "None" return from GetSymbolsInStackFrame

server/JsDbg.Gdb/GdbDebugger.cs
GdbDebugger.cs(534,34): warning CS1998: This async method lacks 'await' operators and will run synchronously. Consider using the 'await' operator to await non-blocking API calls, or 'await Task.Run(...)' to do CPU-bound work on a background thread. [.../JsDbg/server/JsDbg.Gdb/JsDbg.Gdb.csproj]
=> [gdb] Fix the last remaining compiler warning

server/JsDbg.Gdb/GdbDebugger.cs, server/JsDbg.Gdb/JsDbg.py
=> [gdb] Fix bugs in GetCallStack and GetSymbolsInStackFrame

server/JsDbg.Gdb/JsDbg.py, server/JsDbg.Gdb/create_package.sh
This adds a script to package JsDbg into a .tar.bz2 file ready
for extracting in the home directory. It also makes JsDbg.py search
for the binary and extensions in ~/jsdbg where the file would
be extracted to.
Note, this requires pull request #91 to be useful.
=> [gdb] Add a script to package JsDbg for GDB

extensions/target-specific/chromium/blink/fragment-tree/fragment-tree.js
It's never null. See discussion in https://github.com/MicrosoftEdge/JsDbg/pull/93
=> [fragment tree] Don't nullcheck the root layout object (=LayoutView)

extensions/target-specific/chromium/ax-tree/ax-tree.js, extensions/target-specific/stl-helpers/stl-helpers.js
And make ax-tree use the extended field instead of directly accessing
the hashtable, so that it also works with a different STL implementation.
Note, this does not quite make ax-tree work on Linux yet, still figuring
out why.
=> Support std::__Cr::unordered_map and std::__Cr::vector

server/JsDbg.Gdb/JsDbg.py
It is difficult to get them right. In particular, this makes us
handle char[] correctly.
=> [gdb] Let gdb handle converting types to strings

server/JsDbg.Gdb/GdbDebugger.cs, server/JsDbg.Gdb/JsDbg.py
I've convinced myself that always subtracting 2*pointer size is the right
thing, because GDB always generates that offset.
Also, there is no need to wait for a breakpoint because many commands
work even while the program is running. Even if we decide to add
such queuing, it would be better to implement it server-side because
C# has better support for that kind of asynchronicity.
=> [gdb] Resolve two TODOs

server/JsDbg.Gdb/Program.cs
Ctrl+C is a useful command in GDB (e.g. to interrupt program execution),
and we should not exit the server in that case.
Fixes: #102
=> [gdb] Don't exit on Ctrl+C

server/JsDbg.Gdb/JsDbg.py
As per https://sourceware.org/gdb/current/onlinedocs/gdb/Registers.html, GDB provides a
virtual 'fp' register for the frame pointer. Unlike 'rbp' this should
work on x86, x64 and ARM, though I've only tested this on x64 and x86.
=> [gdb] Use virtual 'fp' register for the frame pointer

server/JsDbg.Gdb/JsDbg.py
We did not correctly track the offset of recursive base
classes that did not start at offset 0. This is visible,
for example, in the ref_count_ field of ComputedStyle.
With this change, we correctly display it (and sort it
at the end)
=> [gdb] Fix handling of GetBaseTypes and multiple inheritance

server/JsDbg.Gdb/GdbDebugger.cs, server/JsDbg.Gdb/JsDbg.py
This is a lot more concise than doing it in C# and should
make it easier to adapt this to LLDB in the future.
=> [gdb] Do string parsing for LookupSymbolName in Python

server/JsDbg.VisualStudio/JsDbg.VisualStudio.csproj, server/JsDbg.VisualStudio/app.config, server/JsDbg.VisualStudio/packages.config, server/JsDbg.VisualStudio/source.extension.vsixmanifest
To support building JsDbg.VisualStudio on both VS 2017 and 2019, changed  "Microsoft.VisualStudio.Shell.Framework" from version 15 to a reference to the latest version (16.0.28729) of the "Microsoft.VisualStudio.Shell.Framework" NuGet package. Installing that NuGet package introduces the rest of the references being added here.
To enable the JsDbg vsix to work on VS 2019, changed the installation and prerequisite targets to include the latest version of VS.
=> JsDbg.VisualStudio: Add JsDbg support for VS 2019

extensions/target-specific/stl-helpers/stl-helpers.js
This is used by Chrome when not using a component build, and always on Windows.
=> [stl] Also allow std::__1 as a libc++ namespace

extensions/target-specific/chromium/chromium-helpers/chromium-helpers.js
On Linux, Chrome does not use chrome_child; move chrome to multi-process
modules so that blink-helpers and wtf-helpers work correctly.
=> Make "chrome" a multi-process module

server/JsDbg.Gdb/JsDbg.py
In Python 2, integers can be int or long, and if they are long,
the default string conversion adds an L to the end, which C#
can't parse. Instead, format them using '%d' which does not
have that issue.
=> [gdb] Format thread and process IDs using '%d'

server/JsDbg.Gdb/JsDbg.py
GDB assigns non-running inferiors a PID of 0; filter them out
as they are not useful.
=> [gdb] Filter out inferiors that are not running

extensions/target-specific/chromium/blink/fragment-tree/fragment-tree.js
They are not usually the most interesting part of the tree; this
makes the tree visually easier to scan.
=> [fragment-tree] Show NGLinkStorage in grey

server/JsDbg.VisualStudio/AutoUpdater.cs, server/JsDbg.VisualStudio/JsDbg.VisualStudio.csproj
The URLs don't work, and updating a developer's local build doesn't
seem desirable anyway.
=> Don't try to auto-update on non-deploy builds

server/JsDbg.WinDbg/Program.cs
Makes it a bit easier for users.
=> Show an example WinDbg commandline to start a server.

extensions/dbgobject/arrays/arrays.js
resultingTypeOrFn can actually return a DbgObjectType as well. Also,
documents how the function works.
=> Clarify the documentation of AddArrayField

extensions/target-specific/chromium/blink/blink-helpers/blink-helpers.js, extensions/target-specific/chromium/blink/fragment-tree/fragment-tree.js
In https://crrev.com/c/1621829, NGLinkStorage was renamed. Change
blink-helpers and fragment-tree accordingly, accepting either name.
=> Adapt code to NGLinkStorage -> NGLink rename

extensions/dbgobject/type/dbgobject-type.js
These can be returned by GDB. volatile can be ignored, and
references should be converted to pointers.
=> Handle references and volatile in DbgObjectType

extensions/callstack-dashboard/callstack-dashboard.js, extensions/callstack/callstack.js
It was using old APIs in a couple of places. This change also
makes it handle the case when we can't find a symbol for a
stack frame.
=> [callstack] Fix the callstack-dashboard extension

server/JsDbg.Gdb/JsDbg.py
If we don't have symbols for a frame, block() throws an exception. Instead,
just return an empty list.
=> [gdb] Make GetSymbolsInStackFrame work in frames without symbols

server/JsDbg.Gdb/JsDbg.py
When using "rr pack" rr uses a different name for binaries/libraries,
accept that as well.
=> [gdb] Also accept a different name for rr binaries

server/JsDbg.Gdb/GdbDebugger.cs, server/JsDbg.Gdb/JsDbg.py
Using the module for the pc address matches what DiaDebugger does.
(Should it use IDiaSymbol::get_libraryName instead?)
=> [gdb] Have GetSymbolsInStackFrame return the right module

docs/CONTRIBUTING.md
After 6dda4d5fd149912ee41ebf3846548d6741d1ddf0, the .NET Core SDK is required.
=> Update build requirements

server/JsDbg.Gdb/JsDbg.py
Some versions of GDB seem to serialize types with a class/struct/etc
prefix; remove it here to not confuse JsDbg.
=> [gdb] Remove class/struct/etc from type name

extensions/target-specific/stl-helpers/stl-helpers.js
This fixes the AXTree viewer on Windows.
Based on @cbiesinger 's comment in #143, the spacing between parameters and pointer *'s doesn't matter with gdb. However, with WinDBG they do matter, so this change adjusts the spacing to match WinDBG's expectations.
=> Adjusting spaces to match Windows binary expectations

server/JsDbg.Gdb/JsDbg.py
I made a mistake in b2e2fefcf1f3be92ad996b2702eef8c1e7eac712;
the search path needs to be different for a checkout vs
an installed path.
=> [gdb] Fix incorrect search path

server/JsDbg.Gdb/Makefile
We want the extensions in the extensions/ directory, not
extensions/extensions.
=> [gdb] Fix mistake in "make install"

extensions/tree-inspector/field-selector/field-selector.css, extensions/tree-inspector/field-selector/field-selector.js
When showing multiple variables in the tree display, this
makes it easier to scan the display for the value vs the
path.
Bug: #126
=> Show the variable path more subtly

server/JsDbg.Gdb/JsDbg.py
Some versions of GDB will format this as:
JsDbg [received command]: DebuggerQuery(213,'LookupField("msedge_child","scoped_refptr<blink::NGLayoutResult const>", "ptr_")')
JsDbg [sending response]: 213~{0#8#0#0#ptr_#const class blink::NGLayoutResult *}
Allow the regex to match that too.
=> [gdb] Allow 'class' to show up after the beginning

server/JsDbg.Gdb/JsDbg.py
fullmatch doesn't exist in Python 2.
=> [gdb] Use re.match(^..$) instead of re.fullmatch

server/JsDbg.Gdb/JsDbg.py
It returns a string now. Fixes an error in Python 2.
=> [gdb] Use %s to format the result from GetTargetProcess

server/JsDbg.Gdb/JsDbg.Gdb.csproj
They're not necessary and make offline building fail.
=> [gdb] Remove RuntimeIdentifiers from JsDbg.Gdb project file

server/JsDbg.Gdb/JsDbg.py
Non-standalone ones only produce a .dll and need to run via "dotnet".
=> [gdb] Let JsDbg.py handle both standalone and non-standalone builds

server/JsDbg.Gdb/JsDbg.py, server/JsDbg.Gdb/JsDbg_test.py
This also makes GetModuleForName a lot simpler.
A side-effect of this is that non-main modules will now show up correctly
when running under rr.
=> [gdb] Unify module formatting between GetModuleForName and FormatModule

server/JsDbg.Gdb/Makefile, server/JsDbg.Gdb/testsuite/README, server/JsDbg.Gdb/testsuite/jsdbg.tests/basic.exp, server/JsDbg.Gdb/testsuite/rungdb.sh, server/JsDbg.Gdb/testsuite/site.exp, server/JsDbg.Gdb/testsuite/test_program.cc
This tests that GDB successfully loads the python script and that its
various functions work correctly on a test program.
Uses the "dejagnu" tool, which has poor documentation but
seems otherwise well suited to testing command-line interfaces
like this one (gdb uses it for its tests too).
=> [gdb] Add an integration test

server/JsDbg.Gdb/JsDbg.py
This makes it work for GDBs compiled with Python 2 as well
as Python 3.
=> [gdb] Make WriteMemoryBytes compatible with Python 2

server/JsDbg.Gdb/JsDbg.py, server/JsDbg.Gdb/testsuite/jsdbg.tests/basic.exp
When a variable is optimized out, we can't access its address; this
change makes us handle that case by not returning such variables
from GetSymbolsInStackFrame and adjusts the test accordingly.
=> [gdb] Handle the case of optimized-out variables

server/JsDbg.Gdb/JsDbg.py, server/JsDbg.Gdb/JsDbgTypes.py
This allows reusing them for a future LLDB implementation
=> [gdb] Move SFoo type definitions to a separate file

docs/CONTRIBUTING.md, server/JsDbg.Gdb/Makefile
This is probably more likely to work, especially if users install dotnet
using the package manager.
=> [gdb] Look for dotnet in the path by default

debian/rules
We also no longer need to set DOTNET as of 92f43b329822a5e34911b8820b20f8d5fa53e4b1
=> [gdb] Don't repeat RESTOREFLAGS in debian/rules

docs/CONTRIBUTING.md, server/JsDbg.Gdb/JsDbg.py
This is an easier-to-use way to set verbosity.
=> [gdb] Add a GDB parameter to control verbose output

server/JsDbg.Gdb/Makefile, server/JsDbg.Stdio/JsDbgBase.py
I did not update this target in e391967
The rename makes it clearer that this does not build a .deb
dist is a common name in automake:
https://www.gnu.org/software/automake/manual/html_node/Preparing-Distributions.html
=> [gdb] Fix "make package" and rename to "make dist"

Makefile, debian/README.source, debian/changelog, debian/source/format
If we configure this as a native package, we don't need to use
git-buildpackage, which means we don't need to worry about creating git tags.
A "native" package means that the debian/ directory is part of the original
source, which is what we have. ("Normal" debian packages have the debian
packaging scripts separately from the upstream source code)
Also mention the dejagnu build requirement.
=> [gdb] Simplify .deb build procedure

server/JsDbg.Gdb/Makefile
The current makefile implementation doesn't work with certain sh shell versions. So we use the bash shell so that the makefile works more consistently for everyone.
=> Use bash shell for makefile

server/JsDbg.Gdb/JsDbg.py, server/JsDbg.Stdio/StdioDebugger.cs
This makes GDB's module handling behave more similar to the one in
Windows:
- With all GDB versions, we check if a module is loaded before looking
it up in GDB.
- In GDB 8.4+ (not yet released), we only look for a type/symbol in the
requested module (this is not possible in older GDB versions).
=> [gdb] Better module handling

Makefile, debian/control, debian/rules
Unfortunately this will still put a .changes file in the parent
directory and I don't know how to make it not do that.
Also renames the resulting deb to "jsdbg-gdb.deb" (and ensures that
the package name is changed to that)
=> [gdb] Put the resulting deb in the current directory

server/JsDbg.Stdio/JsDbgBase.py
This missing initialization means we throw an exception when the server
exits, instead of showing a message and clearing the jsdbg global.
=> [gdb] Initialize self.server_exited_func

server/JsDbg.Gdb/JsDbg.py
The JsDbg frontend will call GetAllFields even for types such as
'char'. For such types, accessing .fields() will throw an exception,
which makes the Objdiff extension fail. Instead, just return [].
=> [gdb] Don't throw an exception for types that have no fields

server/JsDbg.Gdb/JsDbg.py
When compiled with clang, for a typedef to an anonymous union, gdb
will not be able to find a name and so 'name' is None. When that
happens, we should just not call strip_typedefs to keep a name
to refer to the type.
Because this only happens with clang, I have not written a testcase
for this bug. I did file a clang bug (see link in comment).
This shows up with base::internal::LockImpl::NativeHandle.
=> [gdb] Better handle typedefs to anonymous unions

server/JsDbg.Gdb/JsDbg.py, server/JsDbg.Gdb/testsuite/jsdbg.tests/basic.exp, server/JsDbg.Gdb/testsuite/test_program.cc
In particular, for a typedef to a pointer, the stripped type will have
no name (it's a pointer to a type with a name). Allow for that.
Followup to 4ba3725f48cc2ec91ea9c6eab5cdf88228abe656
=> Allow empty names for non-struct/union types

extensions/target-specific/chromium/cclayertree/cclayertree.js
This change (https://chromium.googlesource.com/chromium/src/+/3433ee045916f591c95686289606a102c87d2ae9) turned the RenderWidget pointer on RenderViewImpl into a unique ptr, which broke GetRoots for the CCLayerTree extension. Fixing this by adding a call to dereference the unique ptr.
=> CCLayerTree: Fix GetRoots to work with a unique ptr for render widget

extensions/target-specific/chromium/blink/blink-helpers/blink-helpers.js
BlinkHelpers: Add a type description to view the text of a NGPhysicalTextFragment
=> Add type descriptions to view the text of blink::LayoutText and blink::NGPhysicalTextFragment

server/JsDbg.Gdb/JsDbg.py
Unfortunately, thread/process change events won't work, but it's
probably better than throwing an exception.
=> Support older GDB versions

server/JsDbg.Gdb/JsDbg.py, server/JsDbg.Gdb/JsDbg_test.py
This also prints some instructions for setting up SSH port forwarding.
I've also used this opportunity to set things up such that pressing Enter will
not repeat the jsdbg command.
=> Don't open a browser when $DISPLAY is not set

extensions/dbgobject/core/dbgobject.js, extensions/jsdbg/core/jsdbg.js, extensions/target-specific/chromium/blink/blink-helpers/blink-helpers.js, server/JsDbg.Core/IDebugger.cs, server/JsDbg.Core/WebServer.cs, server/JsDbg.Stdio/StdioDebugger.cs, server/JsDbg.Windows/DiaDebugger.cs
The `DbgObject.global` API takes a scope parameter; however, it is currently ignored on Windows. With the latest compiler changes affecting Chromium symbols like `g_frame_map`, the scope now needs to be considered when querying for symbols on Windows. To that end, this change adjusts the symbol name to include the scope prefix before querying the debugger/symbol files on Windows.
There is an additional complication that needs to be addressed to handle anonymous namespaces correctly. On Linux, an anonymous namespace is annotated as `(anonymous namespace)`, whereas on Windows, it is annotated as `` `anonymous namespace'``. To handle this discrepancy, the `DbgObject.global` API now takes an array of scope strings (ordered [outermost scope, ..., innermost scope]), and within this array, an …
=> Support global lookup of symbols within scopes (namespaces, outer classes, etc.) on Windows

debian/control, server/JsDbg.Gdb/Makefile
- Depend on the .NET SDK 5.0 instead of 2.2
- Run the Python 2 tests using `python2` instead of just `python`
=> Modernize debian packaging

debian/rules, server/JsDbg.Gdb/Makefile
As described in https://github.com/dotnet/sdk/issues/2526. Otherwise,
`dotnet publish` returns with exit status 1 during `make install`.
=> Use -maxcpucount:1 to fix debian build
